# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cctv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_background = QtWidgets.QFrame(self.frame)
        self.frame_background.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.frame_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_background.setObjectName("frame_background")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_background)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_nav = QtWidgets.QFrame(self.frame_background)
        self.frame_nav.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_nav.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: #000000ff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        Fpath = (r"C:\Users\Bebo\Desktop\final_project\icons")
        self.frame_nav.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_nav.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_nav.setObjectName("frame_nav")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_nav)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_nav)
        self.label_2.setMinimumSize(QtCore.QSize(70, 70))
        self.label_2.setMaximumSize(QtCore.QSize(70, 70))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(Fpath+"\cctv-logo.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame_nav)
        self.label.setStyleSheet("font:87 12pt \"Arialn Black\";\n"
"color:#58D68D ;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_hide = QtWidgets.QPushButton(self.frame_nav)
        self.bt_hide.setMinimumSize(QtCore.QSize(70, 70))
        self.bt_hide.setStyleSheet("")
        self.bt_hide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(Fpath+"\minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_hide.setIcon(icon)
        self.bt_hide.setIconSize(QtCore.QSize(70, 70))
        self.bt_hide.setObjectName("bt_hide")
        self.horizontalLayout.addWidget(self.bt_hide)
        self.bt_mini = QtWidgets.QPushButton(self.frame_nav)
        self.bt_mini.setMinimumSize(QtCore.QSize(70, 70))
        self.bt_mini.setStyleSheet("")
        self.bt_mini.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(Fpath+"\minimize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_mini.setIcon(icon1)
        self.bt_mini.setIconSize(QtCore.QSize(70, 70))
        self.bt_mini.setObjectName("bt_mini")
        self.horizontalLayout.addWidget(self.bt_mini)
        self.bt_max = QtWidgets.QPushButton(self.frame_nav)
        self.bt_max.setMinimumSize(QtCore.QSize(70, 70))
        self.bt_max.setStyleSheet("")
        self.bt_max.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(Fpath+"\maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_max.setIcon(icon2)
        self.bt_max.setIconSize(QtCore.QSize(70, 70))
        self.bt_max.setObjectName("bt_max")
        self.horizontalLayout.addWidget(self.bt_max)
        self.bt_close = QtWidgets.QPushButton(self.frame_nav)
        self.bt_close.setMinimumSize(QtCore.QSize(70, 70))
        self.bt_close.setStyleSheet("")
        self.bt_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(Fpath+"\close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon3)
        self.bt_close.setIconSize(QtCore.QSize(70, 70))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout.addWidget(self.bt_close)
        self.verticalLayout_3.addWidget(self.frame_nav)
        self.frame_body = QtWidgets.QFrame(self.frame_background)
        self.frame_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_body)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_side = QtWidgets.QFrame(self.frame_body)
        self.frame_side.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_side.setMaximumSize(QtCore.QSize(100, 1000))
        self.frame_side.setStyleSheet("QFrame{\n"
"background-color:rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"font:87 12pt \"Arialn Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20, 200, 220); \n"
"border-radius:5px;\n"
"border:1px solid #B43434;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:black;\n"
"}")
        self.frame_side.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_side.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_side.setObjectName("frame_side")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_side)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bt_live = QtWidgets.QPushButton(self.frame_side)
        self.bt_live.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_live.sizePolicy().hasHeightForWidth())
        self.bt_live.setSizePolicy(sizePolicy)
        self.bt_live.setMinimumSize(QtCore.QSize(60, 60))
        self.bt_live.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(Fpath+"\live(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_live.setIcon(icon4)
        self.bt_live.setIconSize(QtCore.QSize(50, 50))
        self.bt_live.setCheckable(False)
        self.bt_live.setObjectName("bt_live")
        self.verticalLayout_4.addWidget(self.bt_live)
        self.bt_vechile_search = QtWidgets.QPushButton(self.frame_side)
        self.bt_vechile_search.setMinimumSize(QtCore.QSize(60, 60))
        self.bt_vechile_search.setIconSize(QtCore.QSize(50, 50))
        self.bt_vechile_search.setObjectName("bt_vechile_search")
        self.verticalLayout_4.addWidget(self.bt_vechile_search)
        self.bt_notification = QtWidgets.QPushButton(self.frame_side)
        self.bt_notification.setMinimumSize(QtCore.QSize(60, 60))
        self.bt_notification.setObjectName("bt_notification")
        self.verticalLayout_4.addWidget(self.bt_notification)
        self.bt_old_footage = QtWidgets.QPushButton(self.frame_side)
        self.bt_old_footage.setMinimumSize(QtCore.QSize(60, 60))
        self.bt_old_footage.setObjectName("bt_old_footage")
        self.verticalLayout_4.addWidget(self.bt_old_footage)
        self.bt_history = QtWidgets.QPushButton(self.frame_side)
        self.bt_history.setMinimumSize(QtCore.QSize(60, 60))
        self.bt_history.setObjectName("bt_history")
        self.verticalLayout_4.addWidget(self.bt_history)
        self.horizontalLayout_2.addWidget(self.frame_side)
        self.frame_content = QtWidgets.QFrame(self.frame_body)
        self.frame_content.setStyleSheet("QFrame{\n"
"background-color:rgb(53, 53, 79);\n"
"}\n"
" ")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_live = QtWidgets.QWidget()
        self.page_live.setObjectName("page_live")
        self.label_live = QtWidgets.QLabel(self.page_live)
        self.label_live.setGeometry(QtCore.QRect(70, 90, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_live.setFont(font)
        self.label_live.setStyleSheet("color: rgb(0, 255, 127);")
        self.label_live.setObjectName("label_live")
        self.stackedWidget.addWidget(self.page_live)
        self.page_vechile_search = QtWidgets.QWidget()
        self.page_vechile_search.setObjectName("page_vechile_search")
        self.label_vechile = QtWidgets.QLabel(self.page_vechile_search)
        self.label_vechile.setGeometry(QtCore.QRect(80, 120, 161, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_vechile.setFont(font)
        self.label_vechile.setStyleSheet("color: rgb(0, 255, 127);")
        self.label_vechile.setObjectName("label_vechile")
        self.stackedWidget.addWidget(self.page_vechile_search)
        self.page_notification = QtWidgets.QWidget()
        self.page_notification.setObjectName("page_notification")
        self.label_notification = QtWidgets.QLabel(self.page_notification)
        self.label_notification.setGeometry(QtCore.QRect(60, 110, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_notification.setFont(font)
        self.label_notification.setStyleSheet("color: rgb(0, 255, 127);")
        self.label_notification.setObjectName("label_notification")
        self.stackedWidget.addWidget(self.page_notification)
        self.page_old_footage = QtWidgets.QWidget()
        self.page_old_footage.setObjectName("page_old_footage")
        self.label_old = QtWidgets.QLabel(self.page_old_footage)
        self.label_old.setGeometry(QtCore.QRect(70, 90, 131, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_old.setFont(font)
        self.label_old.setStyleSheet("color: rgb(0, 255, 127);\n"
"")
        self.label_old.setObjectName("label_old")
        self.stackedWidget.addWidget(self.page_old_footage)
        self.page_history = QtWidgets.QWidget()
        self.page_history.setObjectName("page_history")
        self.label_history = QtWidgets.QLabel(self.page_history)
        self.label_history.setGeometry(QtCore.QRect(70, 110, 131, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_history.setFont(font)
        self.label_history.setStyleSheet("color: rgb(0, 255, 127);\n"
"")
        self.label_history.setObjectName("label_history")
        self.stackedWidget.addWidget(self.page_history)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_content)
        self.verticalLayout_3.addWidget(self.frame_body)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 8)
        self.verticalLayout_2.addWidget(self.frame_background)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CCTV SYSTEM"))
        self.bt_vechile_search.setText(_translate("MainWindow", "Vehicle Search"))
        self.bt_notification.setText(_translate("MainWindow", "Notifications"))
        self.bt_old_footage.setText(_translate("MainWindow", "Old Footage"))
        self.bt_history.setText(_translate("MainWindow", "History"))
        self.label_live.setText(_translate("MainWindow", "live"))
        self.label_vechile.setText(_translate("MainWindow", "vechile search"))
        self.label_notification.setText(_translate("MainWindow", "notification"))
        self.label_old.setText(_translate("MainWindow", "old footage"))
        self.label_history.setText(_translate("MainWindow", "history"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
